W&B offline, running your script from this directory will only write metadata locally.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-i9gyqera because the default path (/home/j/jzu/xcliu613/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-uvgoke23 because the default path (/home/j/jzu/xcliu613/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-r0a81yej because the default path (/home/j/jzu/xcliu613/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-8o24iznx because the default path (/home/j/jzu/xcliu613/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
[34m[1mgithub: [0mskipping check (offline)
YOLOv5 ðŸš€ 2021-5-5 torch 1.7.1 CUDA:0 (Tesla V100-SXM2-32GB, 32256.0MB)
                              CUDA:1 (Tesla V100-SXM2-32GB, 32256.0MB)
                              CUDA:2 (Tesla V100-SXM2-32GB, 32256.0MB)
                              CUDA:3 (Tesla V100-SXM2-32GB, 32256.0MB)

Namespace(adam=False, artifact_alias='latest', batch_size=16, bbox_interval=-1, bucket='', cache_images=False, cfg='./models/yolov5l.yaml', data='./data/spaghetti.yaml', device='', entity=None, epochs=1000, evolve=False, exist_ok=False, global_rank=0, hyp='data/hyp.scratch.yaml', image_weights=False, img_size=[1920, 1920], label_smoothing=0.0, linear_lr=False, local_rank=0, multi_scale=False, name='exp', noautoanchor=False, nosave=False, notest=False, project='runs/train', quad=False, rect=False, resume=False, save_dir='runs/train/exp41', save_period=-1, single_cls=False, sync_bn=False, total_batch_size=64, upload_dataset=False, weights='', workers=8, world_size=4)
[34m[1mtensorboard: [0mStart with 'tensorboard --logdir runs/train', view at http://localhost:6006/
Traceback (most recent call last):
  File "/home/j/jzu/xcliu613/.conda/envs/pytorch-gpu/lib/python3.8/site-packages/tensorboard/compat/tensorflow_stub/io/gfile.py", line 196, in makedirs
    os.makedirs(path)
  File "/home/j/jzu/xcliu613/.conda/envs/pytorch-gpu/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: 'runs/train/exp41'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 633, in <module>
    tb_writer = SummaryWriter(opt.save_dir)  # Tensorboard
  File "/home/j/jzu/xcliu613/.conda/envs/pytorch-gpu/lib/python3.8/site-packages/torch/utils/tensorboard/writer.py", line 221, in __init__
    self._get_file_writer()
  File "/home/j/jzu/xcliu613/.conda/envs/pytorch-gpu/lib/python3.8/site-packages/torch/utils/tensorboard/writer.py", line 251, in _get_file_writer
    self.file_writer = FileWriter(self.log_dir, self.max_queue,
  File "/home/j/jzu/xcliu613/.conda/envs/pytorch-gpu/lib/python3.8/site-packages/torch/utils/tensorboard/writer.py", line 61, in __init__
    self.event_writer = EventFileWriter(
  File "/home/j/jzu/xcliu613/.conda/envs/pytorch-gpu/lib/python3.8/site-packages/tensorboard/summary/writer/event_file_writer.py", line 77, in __init__
    tf.io.gfile.makedirs(logdir)
  File "/home/j/jzu/xcliu613/.conda/envs/pytorch-gpu/lib/python3.8/site-packages/tensorboard/compat/tensorflow_stub/io/gfile.py", line 669, in makedirs
    return get_filesystem(path).makedirs(path)
  File "/home/j/jzu/xcliu613/.conda/envs/pytorch-gpu/lib/python3.8/site-packages/tensorboard/compat/tensorflow_stub/io/gfile.py", line 198, in makedirs
    raise errors.AlreadyExistsError(
tensorboard.compat.tensorflow_stub.errors.AlreadyExistsError: Directory already exists
Traceback (most recent call last):
  File "/home/j/jzu/xcliu613/.conda/envs/pytorch-gpu/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/j/jzu/xcliu613/.conda/envs/pytorch-gpu/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/j/jzu/xcliu613/.conda/envs/pytorch-gpu/lib/python3.8/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/home/j/jzu/xcliu613/.conda/envs/pytorch-gpu/lib/python3.8/site-packages/torch/distributed/launch.py", line 255, in main
    raise subprocess.CalledProcessError(returncode=process.returncode,
subprocess.CalledProcessError: Command '['/home/j/jzu/xcliu613/.conda/envs/pytorch-gpu/bin/python3', '-u', 'train.py', '--local_rank=3', '--img', '1920', '--batch', '64', '--epochs', '1000', '--data', './data/spaghetti.yaml', '--cfg', './models/yolov5l.yaml', '--weights', '']' returned non-zero exit status 1.
